apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-resources-string
  title: Deploy Resources using literal string
  description: Deploy Resource to Kubernetes
spec:
  owner: guest
  type: service
  # these are the steps which are rendered in the frontend with the form input
  parameters: []
  steps:
    - id: template
      name: Generating component
      action: fetch:template
      input:
        url: ./skeleton
    - id: apply
      name: apply-manifest
      action: cnoe:kubernetes:apply
      input:
        namespaced: true
        manifestString: |
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: game-demo
          data:
            # property-like keys; each key maps to a simple value
            player_initial_lives: "3"
            ui_properties_file_name: "user-interface.properties"

            # file-like keys
            game.properties: |
              enemy.types=aliens,monsters
              player.maximum-lives=5
            user-interface.properties: |
              color.good=purple
              color.bad=yellow
              allow.textmode=true
        clusterName: local
